const sb=supabase.createClient(SUPABASE_CONFIG.url,SUPABASE_CONFIG.publishableKey);
const $=s=>document.querySelector(s);let jobs=[],editId=null;
async function start(){const {data:{session}}=await sb.auth.getSession();if(session)showPanel();else $("#login").hidden=false}
function showPanel(){$("#login").hidden=true;$("#panel").hidden=false;load()}
$("#loginForm").onsubmit=async e=>{e.preventDefault();const {error}=await sb.auth.signInWithPassword({email:$("#email").value,password:$("#password").value});if(error)$("#loginMsg").textContent=error.message;else showPanel()};
$("#logout").onclick=async()=>{await sb.auth.signOut();location.reload()};
async function load(){const {data,error}=await sb.from("jobs").select("*").order("created_at",{ascending:false});if(error){$("#saveMsg").textContent=error.message;return}jobs=data||[];$("#total").textContent=jobs.length;$("#active").textContent=jobs.filter(x=>x.status==="active").length;$("#rows").innerHTML=jobs.map(j=>`<tr><td>${j.job_id}</td><td>${j.title}</td><td>${j.organization}</td><td>${j.status}</td><td><button onclick="edit('${j.id}')">Edit</button><button onclick="del('${j.id}')">Delete</button></td></tr>`).join("")}
$("#jobForm").onsubmit=async e=>{e.preventDefault();const v=id=>$("#"+id).value.trim();const data={job_id:v("job_id"),title:v("title"),organization:v("organization"),category:$("#category").value,qualification:v("qualification"),age:v("age"),salary:v("salary"),location:v("location"),last_date:$("#last_date").value||null,application_fee:v("application_fee"),selection_process:v("selection_process"),official_link:v("official_link"),description:v("description"),status:"active"};const r=editId?await sb.from("jobs").update(data).eq("id",editId):await sb.from("jobs").insert(data);if(r.error)$("#saveMsg").textContent=r.error.message;else{$("#saveMsg").textContent="Saved!";clearForm();load()}}
window.edit=id=>{const j=jobs.find(x=>String(x.id)===String(id));if(!j)return;editId=id;$("#formTitle").textContent="Edit Job";["job_id","title","organization","qualification","age","salary","location","last_date","application_fee","selection_process","official_link","description"].forEach(k=>$("#"+k).value=j[k]||"");$("#category").value=j.category||"Government";scrollTo(0,0)}
window.del=async id=>{if(confirm("Delete this job?")){const r=await sb.from("jobs").delete().eq("id",id);if(r.error)alert(r.error.message);else load()}}
function clearForm(){editId=null;$("#jobForm").reset();$("#formTitle").textContent="Add New Job";$("#saveMsg").textContent=""}
$("#clear").onclick=clearForm;start();
